// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rpc/storage_node.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{0}
}

func (x *PutChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyExists bool                   `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{1}
}

func (x *PutChunkResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type PutSyntheticChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSyntheticChunkRequest) Reset() {
	*x = PutSyntheticChunkRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSyntheticChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSyntheticChunkRequest) ProtoMessage() {}

func (x *PutSyntheticChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSyntheticChunkRequest.ProtoReflect.Descriptor instead.
func (*PutSyntheticChunkRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{2}
}

func (x *PutSyntheticChunkRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutSyntheticChunkRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PutSyntheticChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlreadyExists bool                   `protobuf:"varint,1,opt,name=already_exists,json=alreadyExists,proto3" json:"already_exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSyntheticChunkResponse) Reset() {
	*x = PutSyntheticChunkResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSyntheticChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSyntheticChunkResponse) ProtoMessage() {}

func (x *PutSyntheticChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSyntheticChunkResponse.ProtoReflect.Descriptor instead.
func (*PutSyntheticChunkResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{3}
}

func (x *PutSyntheticChunkResponse) GetAlreadyExists() bool {
	if x != nil {
		return x.AlreadyExists
	}
	return false
}

type PutChunkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkItem) Reset() {
	*x = PutChunkItem{}
	mi := &file_rpc_storage_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkItem) ProtoMessage() {}

func (x *PutChunkItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkItem.ProtoReflect.Descriptor instead.
func (*PutChunkItem) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{4}
}

func (x *PutChunkItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutChunkItem) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutSyntheticChunkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutSyntheticChunkItem) Reset() {
	*x = PutSyntheticChunkItem{}
	mi := &file_rpc_storage_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutSyntheticChunkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutSyntheticChunkItem) ProtoMessage() {}

func (x *PutSyntheticChunkItem) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutSyntheticChunkItem.ProtoReflect.Descriptor instead.
func (*PutSyntheticChunkItem) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{5}
}

func (x *PutSyntheticChunkItem) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *PutSyntheticChunkItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*PutChunkItem        `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{6}
}

func (x *BatchPutRequest) GetChunks() []*PutChunkItem {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type BatchPutResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedChunks int32                  `protobuf:"varint,1,opt,name=accepted_chunks,json=acceptedChunks,proto3" json:"accepted_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResponse.ProtoReflect.Descriptor instead.
func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{7}
}

func (x *BatchPutResponse) GetAcceptedChunks() int32 {
	if x != nil {
		return x.AcceptedChunks
	}
	return 0
}

type BatchPutSyntheticRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Chunks        []*PutSyntheticChunkItem `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutSyntheticRequest) Reset() {
	*x = BatchPutSyntheticRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutSyntheticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutSyntheticRequest) ProtoMessage() {}

func (x *BatchPutSyntheticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutSyntheticRequest.ProtoReflect.Descriptor instead.
func (*BatchPutSyntheticRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{8}
}

func (x *BatchPutSyntheticRequest) GetChunks() []*PutSyntheticChunkItem {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type BatchPutSyntheticResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedChunks int32                  `protobuf:"varint,1,opt,name=accepted_chunks,json=acceptedChunks,proto3" json:"accepted_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchPutSyntheticResponse) Reset() {
	*x = BatchPutSyntheticResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutSyntheticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutSyntheticResponse) ProtoMessage() {}

func (x *BatchPutSyntheticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutSyntheticResponse.ProtoReflect.Descriptor instead.
func (*BatchPutSyntheticResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{9}
}

func (x *BatchPutSyntheticResponse) GetAcceptedChunks() int32 {
	if x != nil {
		return x.AcceptedChunks
	}
	return 0
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{10}
}

func (x *BatchGetRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type BatchGetMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RequestChunks        int32                  `protobuf:"varint,1,opt,name=request_chunks,json=requestChunks,proto3" json:"request_chunks,omitempty"`
	FoundChunks          int32                  `protobuf:"varint,2,opt,name=found_chunks,json=foundChunks,proto3" json:"found_chunks,omitempty"`
	MissingChunks        int32                  `protobuf:"varint,3,opt,name=missing_chunks,json=missingChunks,proto3" json:"missing_chunks,omitempty"`
	BytesReturned        int64                  `protobuf:"varint,4,opt,name=bytes_returned,json=bytesReturned,proto3" json:"bytes_returned,omitempty"`
	IndexLookupSeconds   float64                `protobuf:"fixed64,5,opt,name=index_lookup_seconds,json=indexLookupSeconds,proto3" json:"index_lookup_seconds,omitempty"`
	EngineGetSeconds     float64                `protobuf:"fixed64,6,opt,name=engine_get_seconds,json=engineGetSeconds,proto3" json:"engine_get_seconds,omitempty"`
	ResponseBuildSeconds float64                `protobuf:"fixed64,7,opt,name=response_build_seconds,json=responseBuildSeconds,proto3" json:"response_build_seconds,omitempty"`
	HandlerTotalSeconds  float64                `protobuf:"fixed64,8,opt,name=handler_total_seconds,json=handlerTotalSeconds,proto3" json:"handler_total_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BatchGetMetrics) Reset() {
	*x = BatchGetMetrics{}
	mi := &file_rpc_storage_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetMetrics) ProtoMessage() {}

func (x *BatchGetMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetMetrics.ProtoReflect.Descriptor instead.
func (*BatchGetMetrics) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{11}
}

func (x *BatchGetMetrics) GetRequestChunks() int32 {
	if x != nil {
		return x.RequestChunks
	}
	return 0
}

func (x *BatchGetMetrics) GetFoundChunks() int32 {
	if x != nil {
		return x.FoundChunks
	}
	return 0
}

func (x *BatchGetMetrics) GetMissingChunks() int32 {
	if x != nil {
		return x.MissingChunks
	}
	return 0
}

func (x *BatchGetMetrics) GetBytesReturned() int64 {
	if x != nil {
		return x.BytesReturned
	}
	return 0
}

func (x *BatchGetMetrics) GetIndexLookupSeconds() float64 {
	if x != nil {
		return x.IndexLookupSeconds
	}
	return 0
}

func (x *BatchGetMetrics) GetEngineGetSeconds() float64 {
	if x != nil {
		return x.EngineGetSeconds
	}
	return 0
}

func (x *BatchGetMetrics) GetResponseBuildSeconds() float64 {
	if x != nil {
		return x.ResponseBuildSeconds
	}
	return 0
}

func (x *BatchGetMetrics) GetHandlerTotalSeconds() float64 {
	if x != nil {
		return x.HandlerTotalSeconds
	}
	return 0
}

type ChunkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkData) Reset() {
	*x = ChunkData{}
	mi := &file_rpc_storage_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkData) ProtoMessage() {}

func (x *ChunkData) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkData.ProtoReflect.Descriptor instead.
func (*ChunkData) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{12}
}

func (x *ChunkData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChunkData) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ChunkData) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*ChunkData           `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Metrics       *BatchGetMetrics       `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetResponse) GetChunks() []*ChunkData {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *BatchGetResponse) GetMetrics() *BatchGetMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type UploadFullFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFullFileChunk) Reset() {
	*x = UploadFullFileChunk{}
	mi := &file_rpc_storage_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFullFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFullFileChunk) ProtoMessage() {}

func (x *UploadFullFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFullFileChunk.ProtoReflect.Descriptor instead.
func (*UploadFullFileChunk) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{14}
}

func (x *UploadFullFileChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadFullFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadFullFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived int64                  `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFullFileResponse) Reset() {
	*x = UploadFullFileResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFullFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFullFileResponse) ProtoMessage() {}

func (x *UploadFullFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFullFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFullFileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{15}
}

func (x *UploadFullFileResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type DownloadFullFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFullFileRequest) Reset() {
	*x = DownloadFullFileRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFullFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFullFileRequest) ProtoMessage() {}

func (x *DownloadFullFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFullFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFullFileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadFullFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DownloadFullFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFullFileChunk) Reset() {
	*x = DownloadFullFileChunk{}
	mi := &file_rpc_storage_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFullFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFullFileChunk) ProtoMessage() {}

func (x *DownloadFullFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFullFileChunk.ProtoReflect.Descriptor instead.
func (*DownloadFullFileChunk) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{17}
}

func (x *DownloadFullFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{18}
}

type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{19}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_rpc_storage_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{20}
}

type PingResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NodeId             string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Role               string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	StorageGranularity string                 `protobuf:"bytes,3,opt,name=storage_granularity,json=storageGranularity,proto3" json:"storage_granularity,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_rpc_storage_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_storage_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_rpc_storage_node_proto_rawDescGZIP(), []int{21}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PingResponse) GetStorageGranularity() string {
	if x != nil {
		return x.StorageGranularity
	}
	return ""
}

var File_rpc_storage_node_proto protoreflect.FileDescriptor

const file_rpc_storage_node_proto_rawDesc = "" +
	"\n" +
	"\x16rpc/storage_node.proto\x12\x03rpc\"9\n" +
	"\x0fPutChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"9\n" +
	"\x10PutChunkResponse\x12%\n" +
	"\x0ealready_exists\x18\x01 \x01(\bR\ralreadyExists\"B\n" +
	"\x18PutSyntheticChunkRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"B\n" +
	"\x19PutSyntheticChunkResponse\x12%\n" +
	"\x0ealready_exists\x18\x01 \x01(\bR\ralreadyExists\"6\n" +
	"\fPutChunkItem\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"?\n" +
	"\x15PutSyntheticChunkItem\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"<\n" +
	"\x0fBatchPutRequest\x12)\n" +
	"\x06chunks\x18\x01 \x03(\v2\x11.rpc.PutChunkItemR\x06chunks\";\n" +
	"\x10BatchPutResponse\x12'\n" +
	"\x0faccepted_chunks\x18\x01 \x01(\x05R\x0eacceptedChunks\"N\n" +
	"\x18BatchPutSyntheticRequest\x122\n" +
	"\x06chunks\x18\x01 \x03(\v2\x1a.rpc.PutSyntheticChunkItemR\x06chunks\"D\n" +
	"\x19BatchPutSyntheticResponse\x12'\n" +
	"\x0faccepted_chunks\x18\x01 \x01(\x05R\x0eacceptedChunks\")\n" +
	"\x0fBatchGetRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"\xf3\x02\n" +
	"\x0fBatchGetMetrics\x12%\n" +
	"\x0erequest_chunks\x18\x01 \x01(\x05R\rrequestChunks\x12!\n" +
	"\ffound_chunks\x18\x02 \x01(\x05R\vfoundChunks\x12%\n" +
	"\x0emissing_chunks\x18\x03 \x01(\x05R\rmissingChunks\x12%\n" +
	"\x0ebytes_returned\x18\x04 \x01(\x03R\rbytesReturned\x120\n" +
	"\x14index_lookup_seconds\x18\x05 \x01(\x01R\x12indexLookupSeconds\x12,\n" +
	"\x12engine_get_seconds\x18\x06 \x01(\x01R\x10engineGetSeconds\x124\n" +
	"\x16response_build_seconds\x18\a \x01(\x01R\x14responseBuildSeconds\x122\n" +
	"\x15handler_total_seconds\x18\b \x01(\x01R\x13handlerTotalSeconds\"_\n" +
	"\tChunkData\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"j\n" +
	"\x10BatchGetResponse\x12&\n" +
	"\x06chunks\x18\x01 \x03(\v2\x0e.rpc.ChunkDataR\x06chunks\x12.\n" +
	"\ametrics\x18\x02 \x01(\v2\x14.rpc.BatchGetMetricsR\ametrics\"=\n" +
	"\x13UploadFullFileChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"?\n" +
	"\x16UploadFullFileResponse\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x03R\rbytesReceived\"-\n" +
	"\x17DownloadFullFileRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DownloadFullFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x0e\n" +
	"\fFlushRequest\"\x0f\n" +
	"\rFlushResponse\"\r\n" +
	"\vPingRequest\"l\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12/\n" +
	"\x13storage_granularity\x18\x03 \x01(\tR\x12storageGranularity2\xd8\x04\n" +
	"\vStorageNode\x127\n" +
	"\bPutChunk\x12\x14.rpc.PutChunkRequest\x1a\x15.rpc.PutChunkResponse\x127\n" +
	"\bBatchPut\x12\x14.rpc.BatchPutRequest\x1a\x15.rpc.BatchPutResponse\x12R\n" +
	"\x11PutSyntheticChunk\x12\x1d.rpc.PutSyntheticChunkRequest\x1a\x1e.rpc.PutSyntheticChunkResponse\x12R\n" +
	"\x11BatchPutSynthetic\x12\x1d.rpc.BatchPutSyntheticRequest\x1a\x1e.rpc.BatchPutSyntheticResponse\x127\n" +
	"\bBatchGet\x12\x14.rpc.BatchGetRequest\x1a\x15.rpc.BatchGetResponse\x12I\n" +
	"\x0eUploadFullFile\x12\x18.rpc.UploadFullFileChunk\x1a\x1b.rpc.UploadFullFileResponse(\x01\x12N\n" +
	"\x10DownloadFullFile\x12\x1c.rpc.DownloadFullFileRequest\x1a\x1a.rpc.DownloadFullFileChunk0\x01\x12.\n" +
	"\x05Flush\x12\x11.rpc.FlushRequest\x1a\x12.rpc.FlushResponse\x12+\n" +
	"\x04Ping\x12\x10.rpc.PingRequest\x1a\x11.rpc.PingResponseB\x16Z\x14dedup-system/rpc;rpcb\x06proto3"

var (
	file_rpc_storage_node_proto_rawDescOnce sync.Once
	file_rpc_storage_node_proto_rawDescData []byte
)

func file_rpc_storage_node_proto_rawDescGZIP() []byte {
	file_rpc_storage_node_proto_rawDescOnce.Do(func() {
		file_rpc_storage_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_storage_node_proto_rawDesc), len(file_rpc_storage_node_proto_rawDesc)))
	})
	return file_rpc_storage_node_proto_rawDescData
}

var file_rpc_storage_node_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_rpc_storage_node_proto_goTypes = []any{
	(*PutChunkRequest)(nil),           // 0: rpc.PutChunkRequest
	(*PutChunkResponse)(nil),          // 1: rpc.PutChunkResponse
	(*PutSyntheticChunkRequest)(nil),  // 2: rpc.PutSyntheticChunkRequest
	(*PutSyntheticChunkResponse)(nil), // 3: rpc.PutSyntheticChunkResponse
	(*PutChunkItem)(nil),              // 4: rpc.PutChunkItem
	(*PutSyntheticChunkItem)(nil),     // 5: rpc.PutSyntheticChunkItem
	(*BatchPutRequest)(nil),           // 6: rpc.BatchPutRequest
	(*BatchPutResponse)(nil),          // 7: rpc.BatchPutResponse
	(*BatchPutSyntheticRequest)(nil),  // 8: rpc.BatchPutSyntheticRequest
	(*BatchPutSyntheticResponse)(nil), // 9: rpc.BatchPutSyntheticResponse
	(*BatchGetRequest)(nil),           // 10: rpc.BatchGetRequest
	(*BatchGetMetrics)(nil),           // 11: rpc.BatchGetMetrics
	(*ChunkData)(nil),                 // 12: rpc.ChunkData
	(*BatchGetResponse)(nil),          // 13: rpc.BatchGetResponse
	(*UploadFullFileChunk)(nil),       // 14: rpc.UploadFullFileChunk
	(*UploadFullFileResponse)(nil),    // 15: rpc.UploadFullFileResponse
	(*DownloadFullFileRequest)(nil),   // 16: rpc.DownloadFullFileRequest
	(*DownloadFullFileChunk)(nil),     // 17: rpc.DownloadFullFileChunk
	(*FlushRequest)(nil),              // 18: rpc.FlushRequest
	(*FlushResponse)(nil),             // 19: rpc.FlushResponse
	(*PingRequest)(nil),               // 20: rpc.PingRequest
	(*PingResponse)(nil),              // 21: rpc.PingResponse
}
var file_rpc_storage_node_proto_depIdxs = []int32{
	4,  // 0: rpc.BatchPutRequest.chunks:type_name -> rpc.PutChunkItem
	5,  // 1: rpc.BatchPutSyntheticRequest.chunks:type_name -> rpc.PutSyntheticChunkItem
	12, // 2: rpc.BatchGetResponse.chunks:type_name -> rpc.ChunkData
	11, // 3: rpc.BatchGetResponse.metrics:type_name -> rpc.BatchGetMetrics
	0,  // 4: rpc.StorageNode.PutChunk:input_type -> rpc.PutChunkRequest
	6,  // 5: rpc.StorageNode.BatchPut:input_type -> rpc.BatchPutRequest
	2,  // 6: rpc.StorageNode.PutSyntheticChunk:input_type -> rpc.PutSyntheticChunkRequest
	8,  // 7: rpc.StorageNode.BatchPutSynthetic:input_type -> rpc.BatchPutSyntheticRequest
	10, // 8: rpc.StorageNode.BatchGet:input_type -> rpc.BatchGetRequest
	14, // 9: rpc.StorageNode.UploadFullFile:input_type -> rpc.UploadFullFileChunk
	16, // 10: rpc.StorageNode.DownloadFullFile:input_type -> rpc.DownloadFullFileRequest
	18, // 11: rpc.StorageNode.Flush:input_type -> rpc.FlushRequest
	20, // 12: rpc.StorageNode.Ping:input_type -> rpc.PingRequest
	1,  // 13: rpc.StorageNode.PutChunk:output_type -> rpc.PutChunkResponse
	7,  // 14: rpc.StorageNode.BatchPut:output_type -> rpc.BatchPutResponse
	3,  // 15: rpc.StorageNode.PutSyntheticChunk:output_type -> rpc.PutSyntheticChunkResponse
	9,  // 16: rpc.StorageNode.BatchPutSynthetic:output_type -> rpc.BatchPutSyntheticResponse
	13, // 17: rpc.StorageNode.BatchGet:output_type -> rpc.BatchGetResponse
	15, // 18: rpc.StorageNode.UploadFullFile:output_type -> rpc.UploadFullFileResponse
	17, // 19: rpc.StorageNode.DownloadFullFile:output_type -> rpc.DownloadFullFileChunk
	19, // 20: rpc.StorageNode.Flush:output_type -> rpc.FlushResponse
	21, // 21: rpc.StorageNode.Ping:output_type -> rpc.PingResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_rpc_storage_node_proto_init() }
func file_rpc_storage_node_proto_init() {
	if File_rpc_storage_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_storage_node_proto_rawDesc), len(file_rpc_storage_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_storage_node_proto_goTypes,
		DependencyIndexes: file_rpc_storage_node_proto_depIdxs,
		MessageInfos:      file_rpc_storage_node_proto_msgTypes,
	}.Build()
	File_rpc_storage_node_proto = out.File
	file_rpc_storage_node_proto_goTypes = nil
	file_rpc_storage_node_proto_depIdxs = nil
}
