// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: rpc/storage_node.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageNode_PutChunk_FullMethodName          = "/rpc.StorageNode/PutChunk"
	StorageNode_BatchPut_FullMethodName          = "/rpc.StorageNode/BatchPut"
	StorageNode_PutSyntheticChunk_FullMethodName = "/rpc.StorageNode/PutSyntheticChunk"
	StorageNode_BatchPutSynthetic_FullMethodName = "/rpc.StorageNode/BatchPutSynthetic"
	StorageNode_BatchGet_FullMethodName          = "/rpc.StorageNode/BatchGet"
	StorageNode_UploadFullFile_FullMethodName    = "/rpc.StorageNode/UploadFullFile"
	StorageNode_DownloadFullFile_FullMethodName  = "/rpc.StorageNode/DownloadFullFile"
	StorageNode_Flush_FullMethodName             = "/rpc.StorageNode/Flush"
	StorageNode_Ping_FullMethodName              = "/rpc.StorageNode/Ping"
)

// StorageNodeClient is the client API for StorageNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageNodeClient interface {
	PutChunk(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error)
	BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*BatchPutResponse, error)
	PutSyntheticChunk(ctx context.Context, in *PutSyntheticChunkRequest, opts ...grpc.CallOption) (*PutSyntheticChunkResponse, error)
	BatchPutSynthetic(ctx context.Context, in *BatchPutSyntheticRequest, opts ...grpc.CallOption) (*BatchPutSyntheticResponse, error)
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	UploadFullFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFullFileChunk, UploadFullFileResponse], error)
	DownloadFullFile(ctx context.Context, in *DownloadFullFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFullFileChunk], error)
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type storageNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageNodeClient(cc grpc.ClientConnInterface) StorageNodeClient {
	return &storageNodeClient{cc}
}

func (c *storageNodeClient) PutChunk(ctx context.Context, in *PutChunkRequest, opts ...grpc.CallOption) (*PutChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutChunkResponse)
	err := c.cc.Invoke(ctx, StorageNode_PutChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) BatchPut(ctx context.Context, in *BatchPutRequest, opts ...grpc.CallOption) (*BatchPutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPutResponse)
	err := c.cc.Invoke(ctx, StorageNode_BatchPut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) PutSyntheticChunk(ctx context.Context, in *PutSyntheticChunkRequest, opts ...grpc.CallOption) (*PutSyntheticChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutSyntheticChunkResponse)
	err := c.cc.Invoke(ctx, StorageNode_PutSyntheticChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) BatchPutSynthetic(ctx context.Context, in *BatchPutSyntheticRequest, opts ...grpc.CallOption) (*BatchPutSyntheticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPutSyntheticResponse)
	err := c.cc.Invoke(ctx, StorageNode_BatchPutSynthetic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, StorageNode_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) UploadFullFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadFullFileChunk, UploadFullFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[0], StorageNode_UploadFullFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadFullFileChunk, UploadFullFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_UploadFullFileClient = grpc.ClientStreamingClient[UploadFullFileChunk, UploadFullFileResponse]

func (c *storageNodeClient) DownloadFullFile(ctx context.Context, in *DownloadFullFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadFullFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageNode_ServiceDesc.Streams[1], StorageNode_DownloadFullFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadFullFileRequest, DownloadFullFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_DownloadFullFileClient = grpc.ServerStreamingClient[DownloadFullFileChunk]

func (c *storageNodeClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushResponse)
	err := c.cc.Invoke(ctx, StorageNode_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageNodeClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StorageNode_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageNodeServer is the server API for StorageNode service.
// All implementations must embed UnimplementedStorageNodeServer
// for forward compatibility.
type StorageNodeServer interface {
	PutChunk(context.Context, *PutChunkRequest) (*PutChunkResponse, error)
	BatchPut(context.Context, *BatchPutRequest) (*BatchPutResponse, error)
	PutSyntheticChunk(context.Context, *PutSyntheticChunkRequest) (*PutSyntheticChunkResponse, error)
	BatchPutSynthetic(context.Context, *BatchPutSyntheticRequest) (*BatchPutSyntheticResponse, error)
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	UploadFullFile(grpc.ClientStreamingServer[UploadFullFileChunk, UploadFullFileResponse]) error
	DownloadFullFile(*DownloadFullFileRequest, grpc.ServerStreamingServer[DownloadFullFileChunk]) error
	Flush(context.Context, *FlushRequest) (*FlushResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedStorageNodeServer()
}

// UnimplementedStorageNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageNodeServer struct{}

func (UnimplementedStorageNodeServer) PutChunk(context.Context, *PutChunkRequest) (*PutChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutChunk not implemented")
}
func (UnimplementedStorageNodeServer) BatchPut(context.Context, *BatchPutRequest) (*BatchPutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPut not implemented")
}
func (UnimplementedStorageNodeServer) PutSyntheticChunk(context.Context, *PutSyntheticChunkRequest) (*PutSyntheticChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutSyntheticChunk not implemented")
}
func (UnimplementedStorageNodeServer) BatchPutSynthetic(context.Context, *BatchPutSyntheticRequest) (*BatchPutSyntheticResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPutSynthetic not implemented")
}
func (UnimplementedStorageNodeServer) BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedStorageNodeServer) UploadFullFile(grpc.ClientStreamingServer[UploadFullFileChunk, UploadFullFileResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadFullFile not implemented")
}
func (UnimplementedStorageNodeServer) DownloadFullFile(*DownloadFullFileRequest, grpc.ServerStreamingServer[DownloadFullFileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadFullFile not implemented")
}
func (UnimplementedStorageNodeServer) Flush(context.Context, *FlushRequest) (*FlushResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedStorageNodeServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStorageNodeServer) mustEmbedUnimplementedStorageNodeServer() {}
func (UnimplementedStorageNodeServer) testEmbeddedByValue()                     {}

// UnsafeStorageNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageNodeServer will
// result in compilation errors.
type UnsafeStorageNodeServer interface {
	mustEmbedUnimplementedStorageNodeServer()
}

func RegisterStorageNodeServer(s grpc.ServiceRegistrar, srv StorageNodeServer) {
	// If the following call panics, it indicates UnimplementedStorageNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageNode_ServiceDesc, srv)
}

func _StorageNode_PutChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).PutChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_PutChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).PutChunk(ctx, req.(*PutChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_BatchPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).BatchPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_BatchPut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).BatchPut(ctx, req.(*BatchPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_PutSyntheticChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutSyntheticChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).PutSyntheticChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_PutSyntheticChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).PutSyntheticChunk(ctx, req.(*PutSyntheticChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_BatchPutSynthetic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPutSyntheticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).BatchPutSynthetic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_BatchPutSynthetic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).BatchPutSynthetic(ctx, req.(*BatchPutSyntheticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_UploadFullFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageNodeServer).UploadFullFile(&grpc.GenericServerStream[UploadFullFileChunk, UploadFullFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_UploadFullFileServer = grpc.ClientStreamingServer[UploadFullFileChunk, UploadFullFileResponse]

func _StorageNode_DownloadFullFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFullFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageNodeServer).DownloadFullFile(m, &grpc.GenericServerStream[DownloadFullFileRequest, DownloadFullFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageNode_DownloadFullFileServer = grpc.ServerStreamingServer[DownloadFullFileChunk]

func _StorageNode_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageNode_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageNodeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageNode_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageNodeServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageNode_ServiceDesc is the grpc.ServiceDesc for StorageNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.StorageNode",
	HandlerType: (*StorageNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutChunk",
			Handler:    _StorageNode_PutChunk_Handler,
		},
		{
			MethodName: "BatchPut",
			Handler:    _StorageNode_BatchPut_Handler,
		},
		{
			MethodName: "PutSyntheticChunk",
			Handler:    _StorageNode_PutSyntheticChunk_Handler,
		},
		{
			MethodName: "BatchPutSynthetic",
			Handler:    _StorageNode_BatchPutSynthetic_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _StorageNode_BatchGet_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _StorageNode_Flush_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StorageNode_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFullFile",
			Handler:       _StorageNode_UploadFullFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFullFile",
			Handler:       _StorageNode_DownloadFullFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/storage_node.proto",
}
